name: android-tests
on:
    push:
        branches:
            - master
jobs:
  android-tests-job:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      # Need to make gradlew executable
      - name: Make gradlew executable
        working-directory: ./AndroidProject
        run: chmod +x ./gradlew
      
      # Execute unit tests
      - name: Android units tests
        working-directory: ./AndroidProject
        run: ./gradlew testDebugUnitTest
      
      # Integration Tests
      - name: Android integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          working-directory: ./AndroidProject
          script: ./gradlew connectedCheck
      
      # Print a report of the tests
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless