name: android-tests
on:
    push:
        branches:
            - master
jobs:
    android-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Execute unit tests
            - name: Android units tests
              working-directory: ./AndroidProject
              run: ./gradlew testDebugUnitTest
              
            # Show a report of the unit tests results
            - name: Android Test Report
              uses: asadmansr/android-test-report-action@v1.2.0
              if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


    android-integration-tests:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Integration Tests
            - name: Android integration tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 27  # api level > 27 seems to be failing at sdk installation step
                working-directory: ./AndroidProject
                script: ./gradlew connectedCheck