name: android-test
on:
    push:
        branches:
            - master
jobs:
  android-test-job:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: cd AndroidProject ; ./gradlew test