name: android-test
on:
    push:
        branches:
            - master
jobs:
  android-test-job:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          working-directory: ./AndroidProject
          script: chmod +x ./gradlew ; ./gradlew test ; ./gradlew connectedCheck