name: android-test
on:
    push:
        branches:
            - master
jobs:
  android-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Make gradlew executable
        run: cd AndroidProject ; chmod +x ./gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: ./AndroidProject
          script: ./gradlew connectedCheck